PV_CONFIG:
  IMAGE_PV_NAME: 'TEST:IMAGE'
  RESULT_PV_NAME: 'TEST:RES_IMAGE'
  IMAGE_SIZE: [1440, 1080]

ENVIRON_CONFIG:
  EPICS_CA_MAX_ARRAY_BYTES: '20971520'
  CUDA_VISIBLE_DEVICES: '0'
  YOLO_MODEL_PATH: './model/best.pt'
  