PV_CONFIG:
  IMAGE_PV_NAME: 'TEST:IMAGE'
  RESULT_PV_NAME: 'TEST:RES_IMAGE'
  IMAGE_WIDTH: 1440
  IMAGE_HEIGHT: 1080
  YOLO_IMAGE_WIDTH: 1088
  YOLO_IMAGE_HEIGHT: 1088

ENVIRON_CONFIG:
  EPICS_CA_MAX_ARRAY_BYTES: '20971520'
  CUDA_VISIBLE_DEVICES: '0'
  YOLO_MODEL_PATH: './model/best.pt'
  